server {
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location /media/uploads/ {
        proxy_pass https://feed-api-894866134623.us-central1.run.app/media/uploads/;
        proxy_set_header Host feed-api-894866134623.us-central1.run.app;
        proxy_ssl_server_name on;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}
